// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bag: typeof import('./src/components/bag.vue')['default']
    BasketButton: typeof import('./src/components/basket/BasketButton.vue')['default']
    BasketBuyButton: typeof import('./src/components/basket/BasketBuyButton.vue')['default']
    BasketHeader: typeof import('./src/components/basket/BasketHeader.vue')['default']
    BasketItem: typeof import('./src/components/basket/BasketItem.vue')['default']
    BasketLogo: typeof import('./src/components/basket/BasketButton.vue')['default']
    BasketOpenButton: typeof import('./src/components/basket/BasketOpenButton.vue')['default']
    BasketPurchased: typeof import('./src/components/basket/BasketPurchased.vue')['default']
    BasketTotal: typeof import('./src/components/basket/BasketTotal.vue')['default']
    ButtonAddToBasket: typeof import('./src/components/product/ButtonAddToBasket.vue')['default']
    CategoriesNav: typeof import('./src/components/category/CategoriesNav.vue')['default']
    CategoryButton: typeof import('./src/components/category/CategoryButton.vue')['default']
    CategoryItem: typeof import('./src/components/category/CategoryItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    MainLogo: typeof import('./src/components/MainLogo.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductInfo: typeof import('./src/components/product/ProductInfo.vue')['default']
    ProductItem: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductsCategory: typeof import('./src/components/ProductsCategory.vue')['default']
    ProductsHeader: typeof import('./src/components/product/ProductsHeader.vue')['default']
    ProductsList: typeof import('./src/components/product/ProductsList.vue')['default']
    ProductsListHeader: typeof import('./src/components/ProductsListHeader.vue')['default']
    ProductsSection: typeof import('./src/components/ProductsSection.vue')['default']
    ProductsView: typeof import('./src/components/product/ProductsView.vue')['default']
    ProductView: typeof import('./src/components/product/ProductView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingBag: typeof import('./src/components/ShoppingBag.vue')['default']
    ShoppingBasket: typeof import('./src/components/basket/ShoppingBasket.vue')['default']
  }
}
